"""add active_assignments, probing_questions, student_submissions

Revision ID: e81b8b7703ab
Revises: f972e88a37d8
Create Date: 2025-06-16 21:53:09.969149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e81b8b7703ab'
down_revision: Union[str, None] = 'f972e88a37d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_assignments',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.String(), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_active_assignments_session_id'), 'active_assignments', ['session_id'], unique=False)
    op.create_table('probing_questions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('hint', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['assignment_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_probing_questions_id'), 'probing_questions', ['id'], unique=False)
    op.create_table('student_submissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('answers_json', sa.Text(), nullable=False),
    sa.Column('interactions_json', sa.Text(), nullable=True),
    sa.Column('time_spent_json', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['active_assignments.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_submissions_id'), 'student_submissions', ['id'], unique=False)
    op.alter_column('assignment_questions', 'id',
               existing_type=sa.UUID(),
               existing_nullable=False)
    op.alter_column('assignment_questions', 'assignment_id',
               existing_type=sa.UUID(),
               existing_nullable=False)
    op.create_index(op.f('ix_assignment_questions_id'), 'assignment_questions', ['id'], unique=False)
    op.drop_constraint(op.f('assignment_questions_assignment_id_fkey'), 'assignment_questions', type_='foreignkey')
    op.create_foreign_key(None, 'assignment_questions', 'assignments', ['assignment_id'], ['assignment_id'])
    op.add_column('assignments', sa.Column('assignment_id', sa.String(), nullable=False))
    op.alter_column('assignments', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_assignments_assignment_id'), 'assignments', ['assignment_id'], unique=False)
    op.drop_column('assignments', 'due_date')
    op.drop_column('assignments', 'session_id')
    op.drop_column('assignments', 'course_id')
    op.drop_column('assignments', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('assignments', sa.Column('course_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('assignments', sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('assignments', sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_assignments_assignment_id'), table_name='assignments')
    op.alter_column('assignments', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('assignments', 'assignment_id')
    op.drop_constraint(None, 'assignment_questions', type_='foreignkey')
    op.create_foreign_key(op.f('assignment_questions_assignment_id_fkey'), 'assignment_questions', 'assignments', ['assignment_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_assignment_questions_id'), table_name='assignment_questions')
    op.alter_column('assignment_questions', 'assignment_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('assignment_questions', 'id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_index(op.f('ix_student_submissions_id'), table_name='student_submissions')
    op.drop_table('student_submissions')
    op.drop_index(op.f('ix_probing_questions_id'), table_name='probing_questions')
    op.drop_table('probing_questions')
    op.drop_index(op.f('ix_active_assignments_session_id'), table_name='active_assignments')
    op.drop_table('active_assignments')
    # ### end Alembic commands ###
