"""Create assignment tables

Revision ID: f972e88a37d8
Revises: 
Create Date: 2025-06-15 19:23:02.861573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f972e88a37d8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignment_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcqs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('exam_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('subject', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('topic', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('option_a', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('option_b', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('option_c', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('option_d', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('correct_ans', sa.CHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('exam_year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('mcqs_pkey'))
    )
    op.drop_table('assignment_questions')
    op.drop_table('assignments')
    # ### end Alembic commands ###
